<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.eclipse.org/triquetrum" nsPrefix="org.eclipse.triquetrum.workflow">
  <eClassifiers xsi:type="ecore:EClass" name="NamedObj">
    <eOperations name="getContainer" eType="#//NamedObj"/>
    <eOperations name="topLevel" eType="#//NamedObj"/>
    <eOperations name="setProperty">
      <eParameters name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="applyWrappedObject"/>
    <eOperations name="buildWrappedObject"/>
    <eOperations name="getFullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getChild" eType="#//NamedObj">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="welcome">
      <eParameters name="visitor" eType="#//Visitor"/>
      <eParameters name="deep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="new"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wrappedType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wrappedObject" eType="#//PtolemyNamedObj"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deepComplete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//NamedObj"/>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Configure to edit text."/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fontFamily" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Arial"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="italic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="0,0,0,255"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Director" eSuperTypes="#//Attribute">
    <eOperations name="getParameters" upperBound="-1" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//NamedObj">
    <eOperations name="getParameters" upperBound="-1" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputPorts" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputPorts" upperBound="-1"
        eType="#//Port" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeEntity" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relations" upperBound="-1"
        eType="#//Relation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeActor" eSuperTypes="#//CompositeEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="director" eType="#//Director"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//Linkable">
    <eOperations name="canAcceptNewOutsideRelation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="canAcceptNewInsideRelation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiPort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedRelations" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/linkedPorts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insideLinkedRelations"
        upperBound="-1" eType="#//Relation" changeable="false" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outsideLinkedRelations"
        upperBound="-1" eType="#//Relation" changeable="false" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//Linkable">
    <eOperations name="isConnected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="getVertex" eType="#//Vertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedRelations" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/linkingRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkingRelations" upperBound="-1"
        eType="#//Relation" eOpposite="#//Relation/linkedRelations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedPorts" upperBound="-1"
        eType="#//Port" transient="true" eOpposite="#//Port/linkedRelations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="#//Attribute">
    <eOperations name="getLocation" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex" eSuperTypes="#//Location #//Linkable"/>
  <eClassifiers xsi:type="ecore:EDataType" name="PtolemyNamedObj" instanceClassName="ptolemy.kernel.util.NamedObj"/>
  <eClassifiers xsi:type="ecore:EClass" name="Linkable" abstract="true" interface="true"
      eSuperTypes="#//NamedObj">
    <eOperations name="link">
      <eParameters name="relation" eType="#//Relation"/>
    </eOperations>
    <eOperations name="unlink">
      <eParameters name="relation" eType="#//Relation"/>
    </eOperations>
    <eOperations name="isPotentialStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isPotentialEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="start" eType="#//Linkable"/>
    </eOperations>
    <eOperations name="buildWrappedLinks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Visitor" instanceClassName="org.eclipse.triquetrum.workflow.model.util.Visitor"/>
</ecore:EPackage>
