/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tests;

import com.google.inject.Inject;
import org.eclipse.triquetrum.commands.tests.TqclInjectorProvider;
import org.eclipse.triquetrum.commands.tqcl.TriquetrumScript;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(TqclInjectorProvider.class)
@SuppressWarnings("all")
public class TqclParsingTest {
  @Inject
  private ParseHelper<TriquetrumScript> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final TriquetrumScript result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
