/**
 *
 * $Id$
 */
package org.eclipse.triquetrum.workflow.model.validation;

import org.eclipse.graphiti.mm.algorithms.styles.Color;

/**
 * A sample validator interface for {@link org.eclipse.triquetrum.workflow.model.Annotation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AnnotationValidator {
  boolean validate();

  boolean validateText(String value);
  boolean validateFontFamily(String value);
  boolean validateTextSize(int value);
  boolean validateBold(boolean value);
  boolean validateItalic(boolean value);
  boolean validateColor(String value);

  boolean validateColor(Color value);
}
