/**
 *
 * $Id$
 */
package org.eclipse.triquetrum.workflow.model.validation;


/**
 * A sample validator interface for {@link org.eclipse.triquetrum.workflow.model.Color}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ColorValidator {
  boolean validate();

  boolean validateRed(int value);

  boolean validateGreen(int value);

  boolean validateBlue(int value);

  boolean validateRed(double value);
  boolean validateGreen(double value);
  boolean validateBlue(double value);
  boolean validateAlpha(double value);
}
