/*******************************************************************************
 * Copyright (c) 2015 iSencia Belgium NV.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Erwin De Ley - initial API and implementation and/or initial documentation
 *******************************************************************************/
package org.eclipse.triquetrum.workflow.model.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.triquetrum.workflow.model.Entity;
import org.eclipse.triquetrum.workflow.model.Relation;

/**
 * A sample validator interface for {@link org.eclipse.triquetrum.workflow.model.Port}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PortValidator {
  boolean validate();

  boolean validateInput(boolean value);
  boolean validateOutput(boolean value);
  boolean validateLinkedRelations(EList<Relation> value);

  boolean validateMultiPort(boolean value);

  boolean validateContainer(Entity value);
}
