/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.tests

import com.google.inject.Inject
import org.eclipse.triquetrum.commands.tqcl.TriquetrumScript
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(TqclInjectorProvider)
class TqclParsingTest{

	@Inject
	ParseHelper<TriquetrumScript> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
