/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.triquetrum.commands.ui.quickfix;

import org.eclipse.xtext.xbase.ui.quickfix.XtypeQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class TqclQuickfixProvider extends XtypeQuickfixProvider {
}
